// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SunriseSunset
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("solarNoon")]
        public DateTimeOffset SolarNoon { get; set; }

        [JsonProperty("sunrise")]
        public DateTimeOffset Sunrise { get; set; }

        [JsonProperty("sunset")]
        public DateTimeOffset Sunset { get; set; }

        [JsonProperty("sunriseEnd")]
        public DateTimeOffset SunriseEnd { get; set; }

        [JsonProperty("sunsetStart")]
        public DateTimeOffset SunsetStart { get; set; }

        [JsonProperty("dawn")]
        public DateTimeOffset Dawn { get; set; }

        [JsonProperty("dusk")]
        public DateTimeOffset Dusk { get; set; }

        [JsonProperty("nauticalDawn")]
        public DateTimeOffset NauticalDawn { get; set; }

        [JsonProperty("nauticalDusk")]
        public DateTimeOffset NauticalDusk { get; set; }

        [JsonProperty("nightEnd")]
        public DateTimeOffset NightEnd { get; set; }

        [JsonProperty("night")]
        public DateTimeOffset Night { get; set; }

        [JsonProperty("goldenHourEnd")]
        public DateTimeOffset GoldenHourEnd { get; set; }

        [JsonProperty("goldenHour")]
        public DateTimeOffset GoldenHour { get; set; }
    }
}
